#! /bin/sh
# /etc/init.d/drinks
### BEGIN INIT INFO
# Provides:          drinks
# Required-Start:    $remote_fs $syslog
# Required-Stop:     $remote_fs $syslog
# Default-Start:     3 4 5
# Default-Stop:      0 1 6
# Short-Description: Start daemon at boot time
# Description:       Enable service provided by daemon.
### END INIT INFO

case "$1" in
  start)
    echo "Starting drinks process"
    # run application you want to start
    su paula -c 'python3 /home/paula/automated-liquid-mover/rpi_liquid_mover_8pumps/drinks_aio.py &'
    ;;
  stop)
    echo "Stopping drinks process"
    # kill application you want to stop
    pkill -f drinks_aio.py
    ;;
  *)
    echo "Usage: /etc/init.d/drinks {start|stop}"
    exit 1
    ;;
esac
exit 0
